Add CRS constructor.
JuliaGeo/Proj.jl pull request #74
Opened 2022-11-04 11:06 UTC by evetion

2022-11-06 13:45 UTC, visr requested changes
Thanks for working on this. I added some comments.

2022-11-06 13:45 UTC, visr commented on src/crs.jl
> +mutable struct CRS
Would this help with anything?

```suggestion
mutable struct CRS <: GFT.CoordinateReferenceSystemFormat
```

2022-11-06 13:45 UTC, visr commented on test/libproj.jl
> +    crs = Proj.CRS(gftcrs)
Could you add a test for the `Proj.CRS(::AbstractString)` constructor as well?

2022-11-06 13:45 UTC, visr commented on src/crs.jl
> +    crs = proj_create(crs, ctx)
Similarly to my comment in https://github.com/JuliaGeo/Proj.jl/pull/73#pullrequestreview-1169595117, should we check here if what we have created is indeed a CRS, and not say a pipeline? And test that?

2022-11-06 13:45 UTC, visr commented on src/crs.jl
> +end
Do you know if this covers everything? What about PJ_TYPE_TEMPORAL_CRS or PJ_TYPE_COMPOUND_CRS? Could they also be geographic or projected? If we can't be certain, perhaps we should just stick to the PROJ API and add `proj_get_type(::CRS)` for slightly more convenience.

2022-12-14 19:12 UTC, evetion commented on src/crs.jl
> +mutable struct CRS
I don't think so, no.

2022-12-15 08:46 UTC, evetion commented
@rafaqz This PR includes a method to convert between GFT instances, like ArchGDAL.

2022-12-18 20:02 UTC, evetion commented
Not sure why the CRS is suddenly failing, like the PROJ version changed in between. @visr, any thoughts?

2022-12-19 11:11 UTC, visr commented
That's your own show change from #73 ;)

Fixed in 29e341568db021f7c484ca65830e9fe23f4bc915

The new show is better, it shows explicitly it is a no-op (old then new):
```
Transformation
    source: WGS 84
    target: WGS 84
    direction: forward

Transformation noop
    description: Null geographic offset from WGS 84 to WGS 84
    definition: proj=noop ellps=GRS80
    direction: forward
```

2022-12-19 12:13 UTC, evetion commented
LGTM

2022-12-19 19:48 UTC, visr commented
It would be better to directly do this in the style of https://github.com/yeesian/ArchGDAL.jl/pull/349 and https://github.com/JuliaGeo/LibGEOS.jl/pull/149, since this adds a bunch of methods like `proj_get_id_code(crs::CRS) = proj_get_id_code(crs.pj)` that would soon be removed again.

2022-12-19 21:21 UTC, evetion commented
The style being 
`Base.unsafe_convert(::Type{Ptr{Cvoid}}, x::CRS) = x.ptr`
?

2022-12-19 21:26 UTC, visr commented
Yes indeed, then we don't need to take out the pointer ourselves, which is less code and safer for GC.

2022-12-22 20:57 UTC, visr approved these changes

2022-12-22 21:03 UTC, merged